# tokusa - dark green colorscheme for kitty

foreground #d7ffd7
background #0f1510

cursor #d7ffd7
cursor_text_color #0f1510

selection_foreground #0f1510
selection_background #8fd39a

# ANSI colors
color0  #0f1510
color1  #ff6b6b
color2  #8fd39a
color3  #ffd166
color4  #4dabf7
color5  #AF7FDF
color6  #7fdfcf
color7  #d7ffd7
color8  #5f7f62
color9  #ff6b6b
color10 #b7f7c1
color11 #DFAF7F
color12 #4dabf7
color13 #ae58f5
color14 #7fdfaf
color15 #d7ffd7

# Tab bar
tab_bar_background #0f1510
active_tab_foreground #d7ffd7
active_tab_background #182318
inactive_tab_foreground #5f7f62
inactive_tab_background #121a13
